"""updated models

Revision ID: d458c5f46503
Revises: db73c3b82c30
Create Date: 2025-11-29 17:47:30.206308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd458c5f46503'
down_revision: Union[str, Sequence[str], None] = 'db73c3b82c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_replies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_replies', 'created_at')
    # ### end Alembic commands ###
